name: infra-terraform

on:
  push:
    paths:
      - 'modules/ec2/**'
    branches:
      - main

jobs:
  terraform:
    uses: OpsVerseIO/workflow-templates/.github/workflows/infra-terraform.yaml@main